2019-07-14 18:20:38.575 [error] <0.361.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 15000,socket_opts => ...,...},...}) at <0.362.0> exit with reason normal in context child_terminated
2019-07-14 18:20:38.666 [error] <0.361.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 15000,socket_opts => ...,...},...}) at <0.369.0> exit with reason normal in context child_terminated
2019-07-14 18:20:38.666 [error] <0.361.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 15000,socket_opts => ...,...},...}) at <0.369.0> exit with reason reached_max_restart_intensity in context shutdown
2019-07-14 18:44:09.778 [error] <0.349.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.350.0> exit with reason normal in context child_terminated
2019-07-14 18:44:09.868 [error] <0.349.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.357.0> exit with reason normal in context child_terminated
2019-07-14 18:44:09.868 [error] <0.349.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.357.0> exit with reason reached_max_restart_intensity in context shutdown
2019-07-14 18:56:52.167 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.292.0> exit with reason normal in context child_terminated
2019-07-14 18:56:52.255 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.300.0> exit with reason normal in context child_terminated
2019-07-14 18:56:52.255 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.300.0> exit with reason reached_max_restart_intensity in context shutdown
2019-07-14 20:39:20.426 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.292.0> exit with reason normal in context child_terminated
2019-07-14 20:39:20.519 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.299.0> exit with reason normal in context child_terminated
2019-07-14 20:39:20.519 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.299.0> exit with reason reached_max_restart_intensity in context shutdown
