2019-07-15 02:05:36.970 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.292.0> exit with reason normal in context child_terminated
2019-07-15 02:05:37.059 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.300.0> exit with reason normal in context child_terminated
2019-07-15 02:05:37.059 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.300.0> exit with reason reached_max_restart_intensity in context shutdown
2019-07-15 02:10:36.776 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.292.0> exit with reason normal in context child_terminated
2019-07-15 02:10:36.864 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.300.0> exit with reason normal in context child_terminated
2019-07-15 02:10:36.864 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.300.0> exit with reason reached_max_restart_intensity in context shutdown
2019-07-15 02:18:07.495 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.292.0> exit with reason normal in context child_terminated
2019-07-15 02:18:07.589 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.299.0> exit with reason normal in context child_terminated
2019-07-15 02:18:07.589 [error] <0.291.0> Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<"47.244.15.72">>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => ...,...},...}) at <0.299.0> exit with reason reached_max_restart_intensity in context shutdown
